/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package table;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.JTableHeader;
import koneksi.koneksi;
import show.cetak_qr;
import java.util.ArrayList;
import classes.sql;

/**
 *
 * @author PAKUAN-IT
 */
public class popup_transbarang extends javax.swing.JFrame {
private DefaultTableModel tabmode3;
private Connection conn = new koneksi().connect();
public String kode_barang,kode_arr;
int count=0;
String []codes={"","","","","","","","","",""};
public cetak_qr cetak_qr = null;
    /**
     * Creates new form popup_transbarang
     */

    public popup_transbarang() {
           
        initComponents();
        tab_transaksi();
        
    }
    
        public void tab_transaksi(){
            tab_transaksi.setAutoCreateRowSorter(true);
        Object[] Baris = {"Kode Assets","Kategori","Merk","Tipe","Perusahaan","Lokasi","Dept","Status"};        
        //String cariitem=txt_transaksi.getText();
        tabmode3 = new DefaultTableModel(null,Baris);
        try {
            String sql="SELECT trans_barang.kode, kategori.nama, merk.nama, barang.nama, perusahaan.nama, lokasi.nama, department.nama, trans_barang.status"
                    + " FROM trans_barang join kategori on trans_barang.kode_kategori=kategori.kode"
                    + " join merk on trans_barang.kode_merk=merk.kode"
                    + " join barang on trans_barang.kode_barang=barang.kode"
                    + " join perusahaan on trans_barang.kode_perusahaan=perusahaan.kode"
                    + " join lokasi on trans_barang.kode_lokasi=lokasi.kode"
                    + " join department on trans_barang.kode_dept=department.kode "
                    + " order by trans_barang.kode desc";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                tabmode3.addRow(new Object[]{
                hasil.getString(1),
                hasil.getString(2),
                hasil.getString(3),
                hasil.getString(4),
                hasil.getString(5),
                hasil.getString(6),
                hasil.getString(7),
                hasil.getString(8)
            });
            }
            tab_transaksi.setModel(tabmode3);
            tab_transaksi.setDefaultEditor(Object.class, null);

        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"data gagal ditemukan, Kode : "+ e);
            
        }    
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        b_pilih = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab_transaksi = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        perusahaan_b_edit5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_test = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 255, 230));

        jPanel12.setBackground(new java.awt.Color(5, 32, 56));

        b_pilih.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_pilih.setForeground(new java.awt.Color(231, 238, 126));
        b_pilih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_add_24px.png"))); // NOI18N
        b_pilih.setText("   PILIH");
        b_pilih.setIconTextGap(8);
        b_pilih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_pilihMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b_pilih, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(b_pilih, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        tab_transaksi.setBackground(new java.awt.Color(254, 255, 230));
        tab_transaksi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tab_transaksi.setForeground(new java.awt.Color(5, 32, 56));
        tab_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null"
            }
        ));
        tab_transaksi.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tab_transaksi.setOpaque(false);
        tab_transaksi.setRowHeight(25);
        tab_transaksi.setSelectionBackground(new java.awt.Color(5, 32, 56));
        tab_transaksi.setSelectionForeground(new java.awt.Color(231, 238, 126));
        tab_transaksi.setShowHorizontalLines(false);
        tab_transaksi.setShowVerticalLines(false);
        tab_transaksi.getTableHeader().setReorderingAllowed(false);
        tab_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_transaksiMouseClicked(evt);
            }
        });
        tab_transaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tab_transaksiKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tab_transaksi);

        jPanel13.setBackground(new java.awt.Color(5, 32, 56));

        perusahaan_b_edit5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        perusahaan_b_edit5.setForeground(new java.awt.Color(231, 238, 126));
        perusahaan_b_edit5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_back_24px.png"))); // NOI18N
        perusahaan_b_edit5.setText("KEMBALI");
        perusahaan_b_edit5.setIconTextGap(8);
        perusahaan_b_edit5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                perusahaan_b_edit5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(perusahaan_b_edit5, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(perusahaan_b_edit5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        txt_test.setEditable(false);
        txt_test.setColumns(7);
        txt_test.setRows(5);
        txt_test.setAutoscrolls(false);
        txt_test.setBorder(null);
        jScrollPane1.setViewportView(txt_test);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_pilihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_pilihMouseClicked
        // TODO add your handling code here:
        cetak_qr a = new cetak_qr();
        a.kode_barang = kode_barang;
        a.itemTerpilih(kode_barang); 
        this.dispose();
        a.setVisible(true);
        
    }//GEN-LAST:event_b_pilihMouseClicked

    private void tab_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_transaksiMouseClicked
        // TODO add your handling code here:
        int bar=tab_transaksi.getSelectedRow();
        if (count==0){ kode_barang ="'"+ tabmode3.getValueAt(bar,0).toString()+"'"; 
        count=count+1;
        }
        else {kode_barang = kode_barang +", '"+ tabmode3.getValueAt(bar,0).toString()+"'";; count=count+1;}
       // codes[count]=tabmode3.getValueAt(bar,0).toString();
        txt_test.setText(kode_barang);
        
       
//        count=count+1;
        
       /** inisiasi arraylist**/ ArrayList kode_array = new ArrayList ();
        
//        int bar=tab_transaksi.getSelectedRow();
//        kode_array.add(tabmode3.getValueAt(bar,0).toString());
//       
//        for (int i=0;i<kode_array.size();i++){
//            kode_arr=kode_arr+kode_array.get(i);
//        }
//        txt_test.setText(kode_arr);
    }//GEN-LAST:event_tab_transaksiMouseClicked

    private void perusahaan_b_edit5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perusahaan_b_edit5MouseClicked

        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_perusahaan_b_edit5MouseClicked

    private void tab_transaksiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tab_transaksiKeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_tab_transaksiKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popup_transbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popup_transbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popup_transbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popup_transbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new popup_transbarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b_pilih;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel perusahaan_b_edit5;
    private javax.swing.JTable tab_transaksi;
    private javax.swing.JTextArea txt_test;
    // End of variables declaration//GEN-END:variables
}
